name: Build and Deploy Documentation (AWS Cloudfront)
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: {}
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v2
        with:
          version-canonize: false
  run:
    needs:
      - init
    uses: milaboratory/github-ci/.github/workflows/deploy-docs.yaml@v3-beta
    with:
      app-name: MiXCR Docs
      app-name-slug: 'mixcr-com'
      aws-iam-role-to-assume: 'arn:aws:iam::511903394050:role/milab-euce1-prod-github-oidc-role-mixcr-com'
      aws-region: 'us-east-1'
      aws-cloudfront-distribution-id: 'E2N6ZMKDJERTOE'
      aws-cloudfront-s3-bucket-name: 'milab-euce1-prod-eks-s3-mixcr-com'
      notify-telegram: true
    secrets:
      env: |
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
