name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          cache: 'pip'

      - name: Install OS dependencies
        run: sudo apt-get install -y graphviz default-jdk wget

      - name: Downloading PlantUML
        working-directory: /opt/
        run: sudo wget -O plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2022.0/plantuml-1.2022.0.jar

      - name: Creating PlandUML shell script
        run: |
          echo '#!/bin/bash' > /usr/local/bin/plantuml
          echo 'java $PLANTUML_JAVAOPTS -jar /opt/plantuml.jar ${@}' >> /usr/local/bin/plantuml
          chmod +x /usr/local/bin/plantuml

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Building site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: docs.milaboratory.com
